### ISSUE TITLE
No session.rollback() when transaction.abort() is called.

### ISSUE THREAD

**Issue by groner** [zopefoundation/zope.sqlalchemy#14]
When the default setting of `keep_session=False` is used this isn't an issue, because the connection pool will reset the connection before it is used again.  It seems like the session would need to be rolled back when `keep_session=True` is used.

I see that the two phase data manager issues a rollback in `tpc_abort()`.

Is this (`keep_session=True, twophase=True`) just a configuration that nobody uses (perhaps for some reason I've overlooked)?

**Comment by lrowe** [comment]
The `keep_session` functionality was added specifically to support testing, letting you to inspect the session after the transaction has finished. See: https://github.com/zopefoundation/zope.sqlalchemy/blob/master/src/zope/sqlalchemy/README.txt#L181

The `tpc_abort()` method on the two-phase data manager is called when a two-phase commit is aborted after `tpc_prepare()` is called (i.e. another data manager aborted during the prepare phase.) Not calling rollback here would leave the transaction wedged. In Postgres calling prepare disassociates the transaction from the postgres session:

> From the point of view of the issuing session, PREPARE TRANSACTION is not unlike a ROLLBACK command: after executing it, there is no active current transaction, and the effects of the prepared transaction are no longer visible. (The effects will become visible again if the transaction is committed.)

http://www.postgresql.org/docs/9.4/static/sql-prepare-transaction.html

So I don't think there'd be anything left to inspect in the sqlalchemy session following the `tpc_abort()`.

**Comment by groner** [comment]
> Is this (`keep_session=True, twophase=True` ) just a configuration that nobody uses (perhaps for some reason I've overlooked)?

Whoops.  What I meant to write here is `keep_session=True, twophase=False`.  Sorry if that was confusing.

> The keep_session functionality was added specifically to support testing, letting you to inspect the session after the transaction has finished.

I see.  I already have another mechanism to make sure the session gets closed, so `keep_session` looked like the way to go.  I suppose there's no reason I can't let the transaction manager handle it though.  

> The tpc_abort() method on the two-phase data manager is called when a two-phase commit is aborted after tpc_prepare() is called (i.e. another data manager aborted during the prepare phase.) Not calling rollback here would leave the transaction wedged.

This makes sense, but shouldn't rollback be called any time the transaction is aborted?

**Comment by lrowe** [comment]
> I see. I already have another mechanism to make sure the session gets closed, so keep_session looked like the way to go. I suppose there's no reason I can't let the transaction manager handle it though.

If you have special requirements for the session lifecycle then zope.sqlalchemy may not be appropriate for your use case.

> This makes sense, but shouldn't rollback be called any time the transaction is aborted?

Session rollback happens as a side effect to closing the session, so the data manager does not call it directly.
