### ISSUE TITLE
Issue with upcoming release of SQLAlchemy 1.1

### ISSUE THREAD

**Issue by Cito** [zopefoundation/zope.sqlalchemy#15]
Zope.sqlalchemy is calling `session.transaction._iterate_parents()` in [datamanger.py](https://github.com/zopefoundation/zope.sqlalchemy/blob/88fc88370a909822c14860a86ce7ad6b87109fc4/src/zope/sqlalchemy/datamanager.py#L65). Unfortunately, this method has been renamed to `_iterate_self_and_parents()` in SQLAlchemy 1.1 ([see here](https://github.com/zzzeek/sqlalchemy/commit/0a29071b16e1844b5e1d71aead0e8a1ae83b48d0)).

So this should be fixed somehow or things will break when SQLAlchemy 1.1 will be release (soon).

**Comment by mgedmin** [comment]
This is fixed in master, and now it would be good to make a release.

https://pypi.python.org/pypi/zope.sqlalchemy:
> Package Index Owner: chrism, laurencerowe

I'm guessing chrism is @mcdonc, and laurencerowe is @lrowe.

**Comment by ggstuart** [comment]
Hi, I've got this issue in a fresh install of my hitherto working pyramid app. Is the current solution to downgrade SQLAlchemy? If so then to what version do I downgrade?

**Comment by amol-** [comment]
@mgedmin I saw @mcdonc added you as a mainatiner on pypi -> `Package Index Owner: mgedmin, laurencerowe, chrism` it should be possible to roll out a new release fixing this whenever you have spare time to do so

**Comment by mgedmin** [comment]
0.7.7 is released.
