### ISSUE TITLE
ECCN for zope.sqlalchemy

### ISSUE THREAD

**Issue by kkabhi** [zopefoundation/zope.sqlalchemy#28]
If you do not have your software classified with an ECCN, please kindly answer the following questions so that we may self-assess if there may be any prohibition or restriction for export or re-export of this product.
	Does the Software perform any encryption or utilize any encryption processes?  Y/N
I.	If the answer is YES to question (i), please indicate if the encryption is coded into the application or separately called (such as using SSL)
II.	If the answer is YES to question (i), please indicate what function(s) the cryptography/encryption serves
A.	Copyright protection purposes (Includes using a license key/code)
B.	User authentication purposes
C.	A core part of the functionality such as to encrypt databases
D.	To encrypt communications between the software and a host system.

**Comment by icemac** [comment]
> Does the Software perform any encryption or utilize any encryption processes?

`zope.sqlalchemy` neither does any encryption itself nor it uses encryption to provide its API.
Although it is possible to access a database via an encrypted channel (like SSL) or to store data in a database which has been encrypted on client side, this is totally transparent for `zope.sqlalchemy`. It neither decrypts not encrypts any data. It is only a layer in the transport of data from a client application to a database and vice versa.

@kkabhi Is this statement enough to answer your question?
