### ISSUE TITLE
Use SemVer for packaging (eg. 1.2 should have been 2.0)

### ISSUE THREAD

**Issue by leplatrem** [zopefoundation/zope.sqlalchemy#36]
Version 1.2 was released with a number of breaking changes, breaking projects (eg. https://github.com/Kinto/kinto/pull/2296)

(*Drop support for Python 3.4*, *renamed the ZopeTransactionExtension class to ZopeTransactionEvents*)

Would you mind following SemVer for following releases please?

**Comment by jugmac00** [comment]
"Drop support for Python 3.4..." dropped support for Python 3.4 - I know this as I reviewed the PR.

I guess you meant the PR just before: #34

**Comment by Natim** [comment]
> I guess you meant the PR just before: #34

Indeed

**Comment by mgedmin** [comment]
Should we re-release 1.2 as 2.0?

**Comment by mgedmin** [comment]
And also we should add instructions for users about how they should adapt their code to the changelog, see #37.

**Comment by leplatrem** [comment]
> Should we re-release 1.2 as 2.0?

I don't it's necessary. Just let's consider it for the next breaking change!

> And also we should add instructions for users about how they should adapt their code to the changelog, see #37.

Yes, that would definitely be helpful!

**Comment by icemac** [comment]
As a re-release does not seem necessary, I am closing this issue as "won't fix".
Please reopen if needed.
