### ISSUE TITLE
Transitioning to SQLAlchemy 2.0

### ISSUE THREAD

**Issue by tdamsma** [zopefoundation/zope.sqlalchemy#60]
`session.transaction` is deprecated in sqlalchemy 2.0, see here: https://docs.sqlalchemy.org/en/14/orm/session_api.html?highlight=get_transaction#sqlalchemy.orm.Session.get_transaction

So we can use `session.get_transaction()` instead (see #59), but unfortunately this in only available from sqlalchemy 1.4. The minimum supported version is now 0.9, so that's quite a big jump. There probably will be more breaking changes with the transition to 2.0, just haven't run into them yet. Is there a strategy to deal with that?  

My suggestion would be to just update the minimum required version to 1.4 and perhaps fork the latest version with support from 0.9 into some kind of legacy LTS branch.

**Comment by icemac** [comment]
My approach would be to keep compatibility for older versions by checking for the installed SQLAlchemy version.
If we detect additional problems which are harder to solve we still can go the LTS branch route you suggested.

**Comment by tdamsma** [comment]
Ok, I'll give it a shot

**Comment by icemac** [comment]
SQLAlchemy 2.x support was added in #79, fixing also this issue.
