### ISSUE TITLE
Add black

### ISSUE THREAD

**Issue by tdamsma** [zopefoundation/zope.sqlalchemy#63]
Maybe it's just me, but I really find it a regression when I have code linting fail on silly little details. IMHO it is much better to just have black take care of of all that and never think about it again. So is there an opinion on adding black to the toolcahin, and adjusting flake8 and isort config to be compaitbale with default black settings?

**Comment by jugmac00** [comment]
There was a discussion to use `black` for all `zopefoundation` repositories, but it was decided against using it (don't shoot the messenger :-) ), see https://github.com/zopefoundation/meta/issues/6

Also, there was a veto against using `flake8` via `pre-commit`, so you'd notice it at least before commiting, see https://github.com/zopefoundation/Zope/pull/891

What you can... just run `tox` locally - we have a linter env, so at least you do not push non-flake8-conformant code to CI.

**Comment by tdamsma** [comment]
haha, I was kind of expecting this to have been discussed already but didn't imagine it would be so bad. What an awful mess ;)
