### ISSUE TITLE
this library is compatible with SQLAlchemy 1.4 branch on Python 2.7 

### ISSUE THREAD

**Issue by jvanasco** [zopefoundation/zope.sqlalchemy#71]
We still keep an open-source project backwards compatible to Python2.7, and noticed this on a recent test failure:

https://github.com/zopefoundation/zope.sqlalchemy/blob/master/setup.py#L54

This library is still fully functional on Python2.7 with SQLAlchemy 1.4.7+

IMHO, it is worth supporting this combination, as a goal of the 1.4 branch of SQLAlchemy is to help legacy Python2 projects upgrade to Python3 and SQLAlchemy 2.0.

**Comment by icemac** [comment]
@jvanasco Dropping support for SQLAlchemy 1.4 at Python 2.7 does not seem to be necessary. This restriction was probably added because SQLAlchemy 1.4 does not support Python 3.5 any more.

I'll give it a try.

**Comment by icemac** [comment]
I just released https://pypi.org/project/zope.sqlalchemy/1.6/ including this fix.

**Comment by jvanasco** [comment]
Thank you kindly!
